"""add shipping_name to orders

Revision ID: f00f506b3a6b
Revises: fdf5ca1856fe
Create Date: 2026-08-09 12:43:22.848185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00f506b3a6b'
down_revision: Union[str, Sequence[str], None] = 'fdf5ca1856fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_name', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_name')
    # ### end Alembic commands ###
